# Generated by Django 4.2.25 on 2025-10-31 11:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price_from',
        ),
        migrations.CreateModel(
            name='ServiceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255, verbose_name='Имя пациента')),
                ('patient_name_ru', models.CharField(max_length=255, null=True, verbose_name='Имя пациента')),
                ('patient_name_uz', models.CharField(max_length=255, null=True, verbose_name='Имя пациента')),
                ('patient_age', models.IntegerField(blank=True, null=True, verbose_name='Возраст пациента')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('text_ru', models.TextField(null=True, verbose_name='Текст отзыва')),
                ('text_uz', models.TextField(null=True, verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Одобрен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Отзыв по услуге',
                'verbose_name_plural': 'Отзывы по услугам',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/gallery/', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Альтернативный текст')),
                ('alt_text_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Альтернативный текст')),
                ('alt_text_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Альтернативный текст')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Изображение услуги',
                'verbose_name_plural': 'Изображения услуг',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
