# Generated by Django 4.2.25 on 2025-11-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tags_ru',
            field=models.CharField(blank=True, help_text='Через запятую', max_length=500, null=True, verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags_uz',
            field=models.CharField(blank=True, help_text='Через запятую', max_length=500, null=True, verbose_name='Теги'),
        ),
    ]
