# Generated by Django 4.2.25 on 2025-11-22 12:30

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_tags_translation_to_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='description_uz_cyrl',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='organization_uz_cyrl',
            field=models.CharField(max_length=255, null=True, verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='title_uz_cyrl',
            field=models.CharField(max_length=500, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category_uz_cyrl',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_uz_cyrl',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_uz_cyrl',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags_uz_cyrl',
            field=models.CharField(blank=True, help_text='Через запятую', max_length=500, null=True, verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_uz_cyrl',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='book',
            name='author_uz_cyrl',
            field=models.CharField(default='Максудов А.А.', max_length=500, null=True, verbose_name='Автор(ы)'),
        ),
        migrations.AddField(
            model_name='book',
            name='description_uz_cyrl',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='book',
            name='short_description_uz_cyrl',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='book',
            name='title_uz_cyrl',
            field=models.CharField(max_length=500, null=True, verbose_name='Название книги'),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_uz_cyrl',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio_uz_cyrl',
            field=models.TextField(null=True, verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='profile',
            name='clinic_address_uz_cyrl',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес клиники'),
        ),
        migrations.AddField(
            model_name='profile',
            name='clinic_name_uz_cyrl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название клиники'),
        ),
        migrations.AddField(
            model_name='profile',
            name='education_uz_cyrl',
            field=models.TextField(null=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name_uz_cyrl',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialization_uz_cyrl',
            field=models.TextField(null=True, verbose_name='Специализация'),
        ),
        migrations.AddField(
            model_name='profile',
            name='working_hours_uz_cyrl',
            field=models.TextField(blank=True, null=True, verbose_name='Часы работы'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_uz_cyrl',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='funding_uz_cyrl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Финансирование'),
        ),
        migrations.AddField(
            model_name='project',
            name='organization_uz_cyrl',
            field=models.CharField(max_length=255, null=True, verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='project',
            name='results_uz_cyrl',
            field=models.TextField(blank=True, null=True, verbose_name='Результаты'),
        ),
        migrations.AddField(
            model_name='project',
            name='role_uz_cyrl',
            field=models.CharField(max_length=255, null=True, verbose_name='Роль в проекте'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_uz_cyrl',
            field=models.CharField(max_length=500, null=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='publication',
            name='abstract_uz_cyrl',
            field=models.TextField(blank=True, null=True, verbose_name='Аннотация'),
        ),
        migrations.AddField(
            model_name='publication',
            name='authors_uz_cyrl',
            field=models.TextField(help_text='ФИО авторов через запятую', null=True, verbose_name='Авторы'),
        ),
        migrations.AddField(
            model_name='publication',
            name='keywords_uz_cyrl',
            field=models.CharField(blank=True, help_text='Через запятую', max_length=500, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_uz_cyrl',
            field=models.CharField(max_length=500, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_uz_cyrl',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_uz_cyrl',
            field=models.CharField(max_length=255, null=True, verbose_name='Название услуги'),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='alt_text_uz_cyrl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Альтернативный текст'),
        ),
        migrations.AddField(
            model_name='servicereview',
            name='patient_name_uz_cyrl',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя пациента'),
        ),
        migrations.AddField(
            model_name='servicereview',
            name='text_uz_cyrl',
            field=models.TextField(null=True, verbose_name='Текст отзыва'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='patient_name_uz_cyrl',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя пациента'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='text_uz_cyrl',
            field=models.TextField(null=True, verbose_name='Текст отзыва'),
        ),
    ]
