# Generated by Django 4.2.25 on 2025-10-31 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_service_price_from_servicereview_serviceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='age',
            field=models.IntegerField(default=30, help_text='Обязательное поле', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='message',
            field=models.TextField(blank=True, verbose_name='Описание проблемы'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='preferred_date',
            field=models.DateField(default='2024-01-01', verbose_name='Предпочтительная дата'),
        ),
    ]
