# Generated by Django 4.2.25 on 2025-11-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_service_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='orcid',
            field=models.CharField(blank=True, help_text='ORCID ID (например: 0000-0000-0000-0000)', max_length=19, verbose_name='ORCID'),
        ),
        migrations.AddField(
            model_name='profile',
            name='researchgate',
            field=models.URLField(blank=True, verbose_name='ResearchGate'),
        ),
    ]
